CREATE TABLE post (
  cd_post INT(11) NOT NULL AUTO_INCREMENT,
  latitude VARCHAR(30) NOT NULL,
  longitude VARCHAR(30) NOT NULL,
  nm_local VARCHAR(200) NOT NULL,
  endereco VARCHAR(500) NOT NULL,
  assunto VARCHAR(100) NOT NULL,
  descricao TEXT NOT NULL,
  cd_usuario INT(11) NOT NULL,
  dt_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dt_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (cd_post),
  FOREIGN KEY (cd_usuario) REFERENCES usuarios (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;